export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";
//////////////
export const FETCH_PROFILE_OF_USER = "FETCH_PROFILE_OF_USER";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_NOT_SUCCESS = "SEND_MESSAGE_NOT_SUCCESS";
export const POST_NEW_EVENT_SUCCESS= "POST_NEW_EVENT_SUCCESS";
export const POST_NEW_EVENT_NOT_SUCCESS = "POST_NEW_EVENT_NOT_SUCCESS";
export const POST_NEW_JOB_SUCCESS = "POST_NEW_JOB_SUCCESS";
export const POST_NEW_JOB_NOT_SUCCESS = "POST_NEW_JOB_NOT_SUCCESS";
export const FETCH_COMPANY_JOB_DATA = "FETCH_COMPANY_JOB_DATA";
export const FETCH_COMPANY_EVENT_DATA = "FETCH_COMPANY_EVENT_DATA";
export const FETCH_REGISTERED_JOB_DATA = "FETCH_REGISTERED_JOB_DATA";
export const CHECK_STUDENT_ELIGIBILITY = "CHECK_STUDENT_ELIGIBILITY";
export const EVENT_ALREADY_APPLIED = "EVENT_ALREADY_APPLIED";
export const EVENT_NOT_APPLIED = "EVENT_NOT_APPLIED";
export const VIEW_STUDENT_PROFILE = "VIEW_STUDENT_PROFILE";
export const FETCH_STUDENT_DATA = "FETCH_STUDENT_DATA";
export const FETCH_JOB_DETAILS_DATA = "FETCH_JOB_DETAILS_DATA";
export const JOB_ALREADY_APPLIED = "JOB_ALREADY_APPLIED";
export const JOB_NOT_APPLIED = "JOB_NOT_APPLIED";
export const FETCH_REGISTERED_EVENT_DATA = "FETCH_REGISTERED_EVENT_DATA";
export const FETCH_EVENT_DATA = "FETCH_EVENT_DATA";
export const FETCH_JOB_DATA = "FETCH_JOB_DATA";
export const FETCH_EVENT_DETAILS_DATA = "FETCH_EVENT_DETAILS_DATA";
export const SAVE_CONTACT_OF_USER = "SAVE_CONTACT_OF_USER";
export const VIEW_EVENT_APPLICANTS = "VIEW_EVENT_APPLICANTS";
export const VIEW_JOB_APPLICANTS = "VIEW_JOB_APPLICANTS";

export const FETCH_COMPANY_PROFILE_DATA = "FETCH_COMPANY_PROFILE_DATA";

export const FETCH_MESSAGE_DATA = "FETCH_MESSAGE_DATA";


///////////////




